<a href="https://colab.research.google.com/github/Msbohra/Case-Statements-SQL/blob/main/FITBIT_Analysis_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
a = np.array([0,1,2,3,4,5])


In [ ]:
mask = (a%2 == 0)

In [ ]:
mask

array([ True, False,  True, False,  True, False])

In [ ]:
a[mask]= -1

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

Fitbit Analysis


In [6]:
data = np.loadtxt("fit.txt", dtype = "str")

In [7]:
len(data)

96

In [8]:
len(data[0])

6

In [9]:
data.shape

(96, 6)

In [ ]:
b= np.arange(16)

In [ ]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
b.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
b.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
##ValueError: cannot reshape array of size 16 into shape (4,5)

In [ ]:
b.reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

this will create 8 rows and automatically find a factor of total numbers in order to fill the columns. -1 is a dumy value


In [ ]:
b.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
b.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

this transpose our one d array

In [ ]:
a = b.reshape(4,4)

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [ ]:
a[0]

array([0, 1, 2, 3])

a[0][0]

In [ ]:
a[0,0] # i row and j column

0

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a[[0,1,2,3],[0,1,2,3]] # a[[row1, row2 , row3, row4], [col1, col2, col3, col4]]

array([ 0,  5, 10, 15])

In [ ]:
a[:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[:,:2] #all the rows and first two columns

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a[2:3,1:]

array([[ 9, 10, 11]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
mask = a[a < 6]

In [ ]:
mask ## answer will always be in one d

array([0, 1, 2, 3, 4, 5])

In [ ]:
a [a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [10]:
data.shape

(96, 6)

In [11]:
data_t = data.T

In [12]:
data_t

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [14]:
step_count = data_t[1]   # just for step count

In [15]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [27]:
step_count = step_count.astype("int")

In [28]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [29]:
step_count.mean()

2935.9375

In [30]:
step_count.min()

25

In [31]:
step_count.max()

7422

In [32]:
data[:,1]

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [34]:
mood = data[:, 2]
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [36]:
s = np.array([300, 457, 2000, 430, 3500])

In [37]:
s

array([ 300,  457, 2000,  430, 3500])

In [38]:
m = np.array(["happy","sad","happy","sad", "happy"])

In [39]:
m

array(['happy', 'sad', 'happy', 'sad', 'happy'], dtype='<U5')

In [40]:
s[m=='happy']

array([ 300, 2000, 3500])

In [43]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.sum(a)

66

In [45]:
# axis = 0 col, axis = 1 row

In [46]:
np.sum(a,axis = 0)

array([12, 15, 18, 21])

In [47]:
np.sum(a, axis = 1)

array([ 6, 22, 38])

In [48]:
np.mean(a, axis = 0)

array([4., 5., 6., 7.])

In [49]:
np.mean(a, axis = 1)

array([1.5, 5.5, 9.5])

In [56]:
a = np.array([4,5,6,7])
b = np.array([4,7,2,1])

In [57]:
a<b

array([False,  True, False, False])

In [58]:
np.any(a<b)

True

In [59]:
np.all(a<b)

False

In [61]:
np.array([0,1,-1,3,5,-4, 8])

array([ 0,  1, -1,  3,  5, -4,  8])

In [62]:
np.where(a>0, -1, 1)

array([-1, -1, -1, -1])

In [65]:
mood_happy = mood =="Happy"
step_count_happy = step_count[mood_happy]
step_count_happy

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [66]:
len(step_count_happy)

40

In [72]:
mood_happy_netural = (mood =="Neutral") | (mood == "Happy")
step_count_happy_netural = step_count[mood_happy_netural]
step_count_happy_netural

array([5464, 6915, 4732, 3158, 4383, 3881, 4037,  202,  292,  330, 2209,
       4550, 4435, 4779, 1831, 2255,  539, 5464, 6041, 4068, 4683, 4033,
       6314,  614, 3149, 4005, 4880, 4136,  705,  570,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 1163, 3608,  774, 1421, 4064,
       2725, 5934, 1867, 2374, 2909, 7102, 3941, 7422,  437, 1231, 4921,
       6500, 3575, 5537, 4108, 5376, 3066, 1447, 2599,  153,  500, 2127,
       2203])

In [73]:
len(step_count_happy_netural)

67

In [74]:
step_count_happy_netural.mean()

3296.4328358208954

In [75]:
mood_sad = (mood =="Sad")
step_count_sad = step_count[mood_sad]
step_count_sad

array([6041,   25, 5461, 4545, 4340, 1230,   61, 1258, 3148, 4687, 3519,
       1580, 2822,  181, 6676, 3721, 1648,  799, 1696,  221, 4061,  651,
        753,  518,  177,   36,  299,  702,  133])

In [77]:
len(step_count_sad)

29

In [78]:
step_count_sad.mean()

2103.0689655172414

What is the step c
ount for the days where mood is happy and active_status is active

```
# This is formatted as code
```



In [84]:
activity_status = data[:, 5 ]

In [89]:
mood_happy_active = (mood == "Happy") & (activity_status == "Active")
step_count_happy_active = step_count[mood_happy_active]
step_count_happy_active

array([4732, 4550,  539, 6314,  614, 3149, 4005, 4880, 4136,  705,  269,
        493,  995, 3608,  774, 1421, 4064, 2725, 5934, 1867, 7422, 5537,
       5376, 2203])

In [90]:
step_count_happy_active.mean()

3179.6666666666665

In [91]:
len(step_count_happy_active)

24

In [ ]:
#argmax #argmin # gives the index of the maximum value

In [92]:
a = np.array([1,2,5,6,10,4])
a.argmin()

0

In [ ]:
## Date where there are maximum step

In [93]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [102]:
date = data[:, 0]
max_step_count = step_count.argmax()
date_max_step_count = date[max_step_count]
date_max_step_count

'14-12-2017'

In [ ]:
##date where there are minimum step_count

In [103]:
date_min_step_count = date[step_count.argmin()]

In [104]:
date_min_step_count

'08-10-2017'

In [105]:
## calories burnt where there are minimum step_count

In [109]:
calories = data[:,3]
calories

array(['181', '197', '0', '174', '223', '149', '140', '38', '1', '40',
       '101', '152', '150', '113', '49', '86', '6', '99', '143', '125',
       '129', '6', '9', '10', '72', '150', '141', '156', '57', '72', '17',
       '181', '197', '131', '154', '137', '193', '19', '101', '139',
       '164', '137', '22', '17', '9', '145', '192', '146', '234', '167',
       '16', '17', '32', '35', '220', '116', '23', '44', '131', '86',
       '194', '60', '121', '76', '93', '53', '25', '227', '125', '243',
       '14', '39', '55', '158', '7', '213', '116', '129', '21', '28',
       '16', '180', '138', '176', '99', '5', '1', '10', '47', '84', '23',
       '4', '0', '0', '0', '0'], dtype='<U10')

In [112]:
calories_min_step_count = calories[step_count.argmin()]
calories_min_step_count

'0'